import type { NextPage } from "next"
import Head from "next/head"

import { getAllPosts } from "@/lib/notionAPI"
import type { Props } from "@/types"

export const getStaticProps = async () => {
  const allPosts = await getAllPosts()

  return {
    props: {
      allPosts,
    },
    revalidate: 60,
  }
}

const Home: NextPage<Props> = ({ allPosts }) => {
  console.info(allPosts)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
    </>
  )
}

export default Home
